# Generated by Django 3.2.16 on 2022-12-15 15:44

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Title')),
                ('upc', models.CharField(blank=True, max_length=12, null=True, verbose_name='Universal Product Code')),
                ('cover', models.ImageField(blank=True, max_length=10000000, null=True, upload_to='media/album_cover/', verbose_name='Cover')),
                ('label', models.CharField(max_length=255, verbose_name='Label')),
                ('duration', models.PositiveIntegerField(verbose_name='Explicit Content Lyrics')),
                ('release_date', models.DateField(blank=True, null=True, verbose_name='Release Date')),
                ('record_type', models.CharField(blank=True, max_length=255, null=True, verbose_name='Record Type')),
                ('available', models.BooleanField(default=True, verbose_name='Available')),
                ('explicit_lyrics', models.BooleanField(default=False, verbose_name='Explicit lyrics')),
                ('explicit_content_lyrics', models.IntegerField(choices=[(0, 'Not Explicit'), (1, 'Explicit'), (2, 'Unknown'), (3, 'Edited'), (4, "Partially Explicit (Album 'lyrics' only)"), (5, "Partially Unknown (Album 'lyrics' only)"), (6, 'No Advice Available'), (7, "Partially No Advice Available (Album 'lyrics' only)")], default=0, verbose_name='Explicit Content Lyrics')),
                ('explicit_content_cover', models.IntegerField(choices=[(0, 'Not Explicit'), (1, 'Explicit'), (2, 'Unknown'), (3, 'Edited'), (4, "Partially Explicit (Album 'lyrics' only)"), (5, "Partially Unknown (Album 'lyrics' only)"), (6, 'No Advice Available'), (7, "Partially No Advice Available (Album 'lyrics' only)")], default=0, verbose_name='Explicit Content Cover')),
            ],
            options={
                'verbose_name': 'Album',
                'verbose_name_plural': 'Albums',
            },
        ),
        migrations.CreateModel(
            name='AlbumFan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'Album Fan',
                'verbose_name_plural': 'Album Fans',
            },
        ),
        migrations.CreateModel(
            name='AlbumGenre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'Genre',
                'verbose_name_plural': 'Genres',
            },
        ),
        migrations.CreateModel(
            name='Artist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
                ('picture', models.ImageField(blank=True, max_length=10000000, null=True, upload_to='media/artist_picture/', verbose_name='Picture')),
                ('radio', models.BooleanField(default=False, verbose_name='Smartradio')),
            ],
            options={
                'verbose_name': 'Artist',
                'verbose_name_plural': 'Artists',
            },
        ),
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
                ('picture', models.ImageField(blank=True, max_length=10000000, null=True, upload_to='media/genre_picture/', verbose_name='Picture')),
            ],
            options={
                'verbose_name': 'Genre',
                'verbose_name_plural': 'Genres',
            },
        ),
        migrations.CreateModel(
            name='Track',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(max_length=781250000000, upload_to='media/track_file/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['mp3', 'wav', 'aac', 'wma'])], verbose_name='File')),
                ('readable', models.BooleanField(default=True, verbose_name='Readable')),
                ('title', models.CharField(max_length=255, verbose_name='Title')),
                ('title_short', models.CharField(blank=True, max_length=100, null=True, verbose_name='Title Short')),
                ('title_version', models.CharField(blank=True, max_length=100, null=True, verbose_name='Title Version')),
                ('isrc', models.CharField(blank=True, max_length=100, null=True, verbose_name='International Standard Recording Code')),
                ('duration', models.IntegerField(verbose_name='Duration')),
                ('track_position', models.IntegerField(verbose_name='Track Position')),
                ('disk_number', models.IntegerField(blank=True, null=True, verbose_name='Disk Number')),
                ('release_date', models.DateField(blank=True, null=True, verbose_name='Release Date')),
                ('explicit_lyrics', models.BooleanField(blank=True, null=True, verbose_name='Explicit lyrics')),
                ('explicit_content_lyrics', models.IntegerField(blank=True, choices=[(0, 'Not Explicit'), (1, 'Explicit'), (2, 'Unknown'), (3, 'Edited'), (4, "Partially Explicit (Album 'lyrics' only)"), (5, "Partially Unknown (Album 'lyrics' only)"), (6, 'No Advice Available'), (7, "Partially No Advice Available (Album 'lyrics' only)")], null=True, verbose_name='Explicit Content Lyrics')),
                ('explicit_content_cover', models.IntegerField(blank=True, choices=[(0, 'Not Explicit'), (1, 'Explicit'), (2, 'Unknown'), (3, 'Edited'), (4, "Partially Explicit (Album 'lyrics' only)"), (5, "Partially Unknown (Album 'lyrics' only)"), (6, 'No Advice Available'), (7, "Partially No Advice Available (Album 'lyrics' only)")], null=True, verbose_name='Explicit Content Cover')),
                ('bpm', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0.0)], verbose_name='Beats Per Minute (BPM)')),
                ('gain', models.DecimalField(decimal_places=4, default=0.0, max_digits=10, validators=[django.core.validators.MinValueValidator(0.0)], verbose_name='Gain')),
                ('album', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='album_track', to='music.album', verbose_name='Album')),
                ('alternative', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='alternative_track', to='music.track', verbose_name='Alternative')),
                ('artist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='artist_track', to='music.artist', verbose_name='Artist')),
            ],
            options={
                'verbose_name': 'Track',
                'verbose_name_plural': 'Tracks',
            },
        ),
        migrations.CreateModel(
            name='Contributor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('album', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='music.album', verbose_name='Album')),
                ('artist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='music.artist', verbose_name='Artist')),
            ],
            options={
                'verbose_name': 'Contributor',
                'verbose_name_plural': 'Contributors',
            },
        ),
        migrations.CreateModel(
            name='ArtistFan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('artist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='artist_fan', to='music.artist', verbose_name='Artist')),
            ],
            options={
                'verbose_name': 'Artist Fan',
                'verbose_name_plural': 'Artist Fans',
            },
        ),
    ]
