# Generated by Django 3.2.16 on 2022-12-15 15:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('music', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='artistfan',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_artist', to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
        migrations.AddField(
            model_name='artist',
            name='fans',
            field=models.ManyToManyField(related_name='artist_fan', through='music.ArtistFan', to=settings.AUTH_USER_MODEL, verbose_name='Fans'),
        ),
        migrations.AddField(
            model_name='albumgenre',
            name='album',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='album_genre', to='music.album', verbose_name='Artist'),
        ),
        migrations.AddField(
            model_name='albumgenre',
            name='genre',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='genre_album', to='music.genre', verbose_name='User'),
        ),
        migrations.AddField(
            model_name='albumfan',
            name='album',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='album_fan', to='music.album', verbose_name='Artist'),
        ),
        migrations.AddField(
            model_name='albumfan',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_album', to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
        migrations.AddField(
            model_name='album',
            name='alternative',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='alternative_album', to='music.album', verbose_name='Alternative'),
        ),
        migrations.AddField(
            model_name='album',
            name='artist',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='artist_album', to='music.artist', verbose_name='Artist'),
        ),
        migrations.AddField(
            model_name='album',
            name='contributors',
            field=models.ManyToManyField(related_name='album_contributor', through='music.Contributor', to='music.Artist', verbose_name='Contributors'),
        ),
        migrations.AddField(
            model_name='album',
            name='fans',
            field=models.ManyToManyField(related_name='album_fan', through='music.AlbumFan', to=settings.AUTH_USER_MODEL, verbose_name='Fans'),
        ),
        migrations.AddField(
            model_name='album',
            name='genres',
            field=models.ManyToManyField(related_name='album_genre', through='music.AlbumGenre', to='music.Genre', verbose_name='Genres'),
        ),
    ]
